name: CI/Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    container: node:${{ matrix.node-version }}
        
    steps:
      - uses: actions/checkout@v2

      - name: Node and Yarn Versions
        run: |
          node --version
          yarn --version
          
      - name: Install using lockfile
        run: yarn install --frozen-lockfile
        
      - name: Run Jest Tests
        run: yarn rw test
        env:
          CI: true
